###  Auth ###
fragment TokenResponse on TokenResponse {
    token
    expiresAt
}

fragment GuestResponse on GuestResponse {
    _id
    invitationLinkId
    phone
    title
    firstName
    lastName
    email
    isOnBoarded
    isInEvent
    isGifted
    createdAt
    updatedAt
    link {
        ...GuestLinkResponse
    }
}

fragment GuestLinkResponse on GuestLinkResponse {
    _id
    guestId
    code
    invitationCardUrl
    type
    status
    createdAt
    updatedAt
    guestUrl
}

fragment InvitationLinkResponse on InvitationLinkResponse{
    _id
    code
    guestSize
    guestPerEntry
    guestsRegistered
    type
    status
    createdAt
    updatedAt
    inviteUrl
    guests {
        ...GuestResponse
    }
}

fragment UserResponse on UserResponse {
    _id
    phone
    firstName
    lastName
    email
    type
    createdAt
    updatedAt
}

fragment OkayResponse on OkayResponse {
    message
    status
}


fragment LoginResponse on LoginResponse {
    user {
        ...UserResponse
    }
    accessToken {
        ...TokenResponse
    }
    refreshToken {
        ...TokenResponse
    }
}

fragment FileResponse on FileResponse{
    _id
    url
    uploadUrl
    isGeneral
    isConfirmed
    createdAt
    updatedAt
    tags {
        ...GuestResponse
    }
}