###  Activations ###
mutation generateInviteLink($input: CreateInvitationLinkInput!) {
    generateInviteLink(input: $input) {
        ...OkayResponse
    }
}

mutation generatePrintCard($input: CreatePrintCardInput!) {
    generatePrintCard(input: $input) {
        ...OkayResponse
    }
}

mutation login($input: LoginInput!) {
    login(input: $input) {
        ...LoginResponse
    }
}


mutation refreshToken {
    refreshToken {
        ...LoginResponse
    }
}

mutation rsvp($input: CreateGuestInput!) {
    rsvp(input: $input) {
        ...GuestResponse
    }
}


### GROUP RENTAL ###

################################################################
############################ PAYMENT ###########################


