###  Activations ###
mutation generateInviteLink($input: CreateInvitationLinkInput!) {
    generateInviteLink(input: $input) {
        ...OkayResponse
    }
}

mutation generatePrintCard($input: CreatePrintCardInput!) {
    generatePrintCard(input: $input) {
        ...OkayResponse
    }
}

mutation login($input: LoginInput!) {
    login(input: $input) {
        ...LoginResponse
    }
}


mutation refreshToken {
    refreshToken {
        ...LoginResponse
    }
}

mutation rsvp($input: CreateGuestInput!) {
    rsvp(input: $input) {
        ...GuestResponse
    }
}

mutation confirmUpload($input: UploadConfirmInput!) {
    confirmUpload(input: $input) {
        ...FileResponse
    }
}

mutation UploadRequest($input: UploadRequestInput!) {
    uploadRequest(input: $input) {
        ...FileResponse
    }
}

mutation sddTagsToFiles($input: TagFileInput!) {
    addTagsToFiles(input: $input) {
        ...FileResponse
    }
}

mutation sddTagsToFiles($input: AttachGuestInput!) {
    attachGuest(input: $input) {
        ...GuestResponse
    }
}

mutation RemoveFileTag($input: RemoveFileTagInput!) {
    removeFileTag(input: $input) {
        _id
    }
}

mutation RemoveFileTag($input: UpdateGuestInput!) {
    updateGuest(input: $input) {
        _id
    }
}

mutation deleteGuest($input: DeleteGuestInput!) {
    deleteGuest(input: $input) {
        _id
    }
}

mutation attachGuest($input: AttachGuestInput!) {
    attachGuest(input: $input) {
        ...GuestResponse
    }
}


### GROUP RENTAL ###

################################################################
############################ PAYMENT ###########################


