################################################################
############################ Guests #############################

query guest($input: FetchGuestInput!) {
    guest(input: $input) {
        ...GuestResponse
    }
}

query guests($limit: Int!, $page: Int!, $search: String!) {
    guests(limit: $limit, page: $page, search: $search) {
        items {
            ...GuestResponse
        }
        limit
        page
    }
}

query invitationLink($input: SimpleInput!) {
    invitationLink(input: $input) {
        ...InvitationLinkResponse
    }
}

query invitationLinks($limit: Int!, $page: Int!, $search: String!, $input: InvitationFilterInput) {
    invitationLinks(limit: $limit, page: $page, search: $search, input: $input) {
        items {
            ...InvitationLinkResponse
        }
        limit
        page
    }
}

query me {
    me {
        ...UserResponse
    }
}

query invitation($input: SimpleInput!) {
    invitation(input: $input) {
        ...GuestLinkResponse
    }
}

query galleryFilesAdmin($input: FetchGalleryInput!, $limit: Int!, $page: Int!, $search: String!) {
    galleryFilesAdmin(input: $input, limit: $limit, page: $page, search: $search) {
        items {
            ...FileResponse
        }
        limit
        page
    }
}
