"""
Indicates exactly one field must be supplied and this field must not be `null`.
"""
directive @oneOf on INPUT_OBJECT

"""Guest Link Response"""
type GuestLinkResponse {
  """Unique Identifier"""
  _id: ID!

  """Parent guest ID"""
  guestId: ID

  """Unique code"""
  code: String!

  """Invitation Card URL"""
  invitationCardUrl: String

  """Link type"""
  type: LinkTypeEnum!

  """Link status"""
  status: LinkStatusEnum!

  """Date created"""
  createdAt: DateTime!

  """Date updated"""
  updatedAt: DateTime!

  """Guest Url"""
  guestUrl: String!

  """Guest data"""
  guest: GuestResponse
}

"""Link Type"""
enum LinkTypeEnum {
  """Public link for multiple guest usage"""
  PUBLIC

  """Private link for single guest"""
  PRIVATE

  """Guest link for invitation purpose only"""
  GUEST

  """Guest code for printed copy only"""
  PRINT
}

"""Link Status"""
enum LinkStatusEnum {
  """Link is not being used"""
  UNUSED

  """Link is currently in use"""
  IN_PROGRESS

  """Link has been used"""
  USED

  """Link is inactive"""
  INACTIVE

  """Link has been generated on a printed invitation card"""
  PRINTED
}

"""
A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
"""
scalar DateTime

"""Guest Response"""
type GuestResponse {
  """Unique Identifier"""
  _id: ID!

  """Parent invitation link ID"""
  invitationLinkId: ID

  """User phone number"""
  phone: String!

  """Guest title"""
  title: String!

  """Guest first name"""
  firstName: String!

  """Guest last name"""
  lastName: String!

  """Guest email"""
  email: String

  """If guest is on boarded"""
  isOnBoarded: Boolean!

  """If guest is in event"""
  isInEvent: Boolean!

  """If guest is gifted"""
  isGifted: Boolean!

  """Date created"""
  createdAt: DateTime!

  """Date updated"""
  updatedAt: DateTime!

  """Associated Guest Link Response"""
  link: GuestLinkResponse
}

type PaginatedGuestResponse {
  """List of GuestResponse"""
  items: [GuestResponse!]

  """Total number of GuestResponse per load"""
  limit: Int!

  """Current page number"""
  page: Int!
}

type UserResponse {
  """Unique Identifier"""
  _id: ID!

  """User phone number"""
  phone: String!

  """User first name"""
  firstName: String

  """User last name"""
  lastName: String

  """User email"""
  email: String

  """User account type"""
  type: UserTypeEnum!

  """Date created"""
  createdAt: DateTime!

  """Date updated"""
  updatedAt: DateTime!
}

"""Specify User type"""
enum UserTypeEnum {
  """Simple user"""
  USER

  """Operator - Technical field operator/support"""
  OPERATOR

  """Admin - Administrator of the system with limited access"""
  ADMIN

  """
  Super Admin - Super Administrator of the entire system with full access
  """
  SUPER_ADMIN

  """
  Chief Admin - Chief Administrator of the entire system with sovereign access
  """
  CHIEF_ADMIN
}

type TokenResponse {
  """Token"""
  token: String!

  """Token expiration time"""
  expiresAt: DateTime!
}

type LoginResponse {
  """User basic data"""
  user: UserResponse!

  """Access token"""
  accessToken: TokenResponse!

  """Refresh Token"""
  refreshToken: TokenResponse!
}

"""Response for OK requests"""
type OkayResponse {
  """Confirmation message"""
  message: String!

  """Status of the request"""
  status: String!
}

"""Invitation Link Response"""
type InvitationLinkResponse {
  """Unique Identifier"""
  _id: ID!

  """Unique code"""
  code: String!

  """Total number of guests allowed for link"""
  guestSize: Int!

  """Total number of guests allowed for each entry"""
  guestPerEntry: Int!

  """Total number of guests registered for link"""
  guestsRegistered: Int!

  """Link type"""
  type: LinkTypeEnum!

  """Link status"""
  status: LinkStatusEnum!

  """Date created"""
  createdAt: DateTime!

  """Date updated"""
  updatedAt: DateTime!

  """Invitation link URL"""
  inviteUrl: String!

  """List of guests for the invitation link"""
  guests: [GuestResponse!]!
}

type PaginatedInvitationLinkResponse {
  """List of InvitationLinkResponse"""
  items: [InvitationLinkResponse!]

  """Total number of InvitationLinkResponse per load"""
  limit: Int!

  """Current page number"""
  page: Int!
}

"""Gallery file response object"""
type FileResponse {
  """Unique Identifier"""
  _id: ID!

  """File URL"""
  url: String!

  """File upload pre-signed URL"""
  uploadUrl: String

  """If file is general"""
  isGeneral: Boolean!

  """If file uploaded"""
  isConfirmed: Boolean!

  """Date created"""
  createdAt: DateTime!

  """Date updated"""
  updatedAt: DateTime!

  """Tagged guests"""
  tags: [GuestResponse!]!
}

type PaginatedGalleryResponse {
  """List of FileResponse"""
  items: [FileResponse!]

  """Total number of FileResponse per load"""
  limit: Int!

  """Current page number"""
  page: Int!
}

type Query {
  """Get user information"""
  me: UserResponse!

  """Get a list of invitation links."""
  invitationLinks(
    """Total number of items per load"""
    limit: Int! = 25

    """Desired page number"""
    page: Int! = 1

    """Search query"""
    search: String! = ""
    input: InvitationFilterInput
  ): PaginatedInvitationLinkResponse!

  """Get a single invitation link."""
  invitationLink(input: SimpleInput!): InvitationLinkResponse!

  """
  Get a single Invitation Card. This could refer to the e-copy or printed copy
  that has/does not yet have an associated guest record
  """
  invitation(input: SimpleInput!): GuestLinkResponse!

  """Get a single guest data. Request made by guest user.."""
  guest(input: FetchGuestInput!): GuestResponse!

  """Get a list of guests"""
  guests(
    """Total number of items per load"""
    limit: Int! = 25

    """Desired page number"""
    page: Int! = 1

    """Search query"""
    search: String! = ""
  ): PaginatedGuestResponse!

  """Get all gallery files"""
  galleryFiles(
    """Total number of items per load"""
    limit: Int! = 25

    """Desired page number"""
    page: Int! = 1

    """Search query"""
    search: String! = ""
    input: FetchGalleryInput!
  ): PaginatedGalleryResponse!

  """Get all gallery files for admin"""
  galleryFilesAdmin(
    """Total number of items per load"""
    limit: Int! = 25

    """Desired page number"""
    page: Int! = 1

    """Search query"""
    search: String! = ""
    input: FetchGalleryInput!
  ): PaginatedGalleryResponse!
}

"""Input type for filtering user support tickets"""
input InvitationFilterInput {
  """Start date for filtering user support"""
  createdSince: DateTime

  """End date for filtering items"""
  createdUntil: DateTime

  """Start date for filtering items by last update"""
  updatedSince: DateTime

  """End date for filtering items by last update"""
  updatedUntil: DateTime

  """Status of the link items"""
  status: LinkStatusEnum

  """Unique code"""
  code: String

  """Total number of guests allowed for link"""
  guestSize: Int

  """Link type"""
  type: LinkTypeEnum

  """Total number of guests allowed for each entry"""
  guestPerEntry: Int

  """Total number of guests registered for link"""
  guestsRegistered: Int
}

"""Simple input Argument with Code"""
input SimpleInput {
  """Unique Identifier"""
  code: String!
}

"""Fetch guest input with guest code and first 3 letter of surname"""
input FetchGuestInput {
  """Guest invitation card code"""
  code: String!

  """Guest first 3 letter of surname"""
  first3Letters: String!
}

"""Fetch guest input with guest code and first 3 letter of surname"""
input FetchGalleryInput {
  """Guest invitation card code"""
  code: String

  """Guest first 3 letter of surname"""
  first3Letters: String
}

type Mutation {
  """Login a returning user"""
  login(input: LoginInput!): LoginResponse!

  """Create an Admin user"""
  createAdmin(input: CreateUserInput!): UserResponse!

  """Refresh user access and refresh tokens.."""
  refreshToken: LoginResponse!

  """Guests details submitted."""
  rsvp(input: CreateGuestInput!): [GuestResponse!]!

  """Attach a guest to an invitation."""
  attachGuest(input: AttachGuestInput!): GuestResponse!

  """Update a guest's details..."""
  updateGuest(input: UpdateGuestInput!): GuestResponse!

  """Generate invitation links for guests."""
  generateInviteLink(input: CreateInvitationLinkInput!): OkayResponse!

  """Generate print cards"""
  generatePrintCard(input: CreatePrintCardInput!): OkayResponse!

  """Delete a single guest data. Request made by guest user.."""
  deleteGuest(input: DeleteGuestInput!): GuestResponse!

  """Get Upload URLs to upload files"""
  uploadRequest(input: UploadRequestInput!): [FileResponse!]!

  """Confirm uploaded files"""
  confirmUpload(input: UploadConfirmInput!): [FileResponse!]!

  """Add tags to files"""
  addTagsToFiles(input: TagFileInput!): [FileResponse!]!

  """Remove tag from files.."""
  removeFileTag(input: RemoveFileTagInput!): FileResponse!
}

"""Login input data"""
input LoginInput {
  """User phone number"""
  phone: String!

  """User password"""
  password: String!
}

input CreateUserInput {
  """User phone number"""
  phone: String!

  """User first name"""
  firstName: String

  """User last name"""
  lastName: String

  """User email"""
  email: String

  """User account type"""
  type: UserTypeEnum!

  """User Password"""
  password: String!
}

"""Create guest input"""
input CreateGuestInput {
  """Guests data"""
  guests: [GuestInput!]!

  """Invitation link ID"""
  invitationLinkId: ID!
}

"""Create guest input"""
input GuestInput {
  """User phone number"""
  phone: String!

  """Guest title"""
  title: String!

  """Guest first name"""
  firstName: String!

  """Guest last name"""
  lastName: String!

  """Guest email"""
  email: String
}

"""Create guest input"""
input AttachGuestInput {
  """Guest data"""
  guest: GuestInput!

  """
  Invitation code extracted from invitation card. Could be from printed or e-copy
  """
  code: String!
}

"""Update guest input"""
input UpdateGuestInput {
  """Unique Identifier"""
  _id: ID

  """Parent invitation link ID"""
  invitationLinkId: ID

  """User phone number"""
  phone: String

  """Guest title"""
  title: String

  """Guest first name"""
  firstName: String

  """Guest last name"""
  lastName: String

  """Guest email"""
  email: String

  """If guest is on boarded"""
  isOnBoarded: Boolean

  """If guest is in event"""
  isInEvent: Boolean

  """If guest is gifted"""
  isGifted: Boolean

  """Date created"""
  createdAt: DateTime

  """Date updated"""
  updatedAt: DateTime
}

"""Create invitation link input"""
input CreateInvitationLinkInput {
  """Total number of guests allowed for link"""
  guestSize: Int! = 1

  """Total number of guests allowed for each entry"""
  guestPerEntry: Int! = 1

  """Link type"""
  type: LinkTypeEnum! = PRIVATE

  """Number of unique links to create"""
  linkCount: Int! = 1
}

"""Create invitation link input"""
input CreatePrintCardInput {
  """Number of unique cards to create"""
  count: Int! = 1
}

"""Delete guest input"""
input DeleteGuestInput {
  """The id of the guest to delete"""
  _id: ID!
}

"""Create upload request input"""
input UploadRequestInput {
  """Number of files to upload"""
  count: Int! = 1

  """List of guest IDs tagged to the upload request files"""
  tagIds: [ID!]! = []

  """Whether the upload request is for general access"""
  isGeneral: Boolean! = false
}

"""Confirmation input for uploaded files"""
input UploadConfirmInput {
  """Ids of the files to be confirmed for upload"""
  ids: [ID!]!
}

"""Input for tagging a file with a guest"""
input TagFileInput {
  """
  IDs of the files being tagged. This enables bulk tagging multiple files at a time
  """
  ids: [ID!]!

  """List of guest IDs tagged to the upload request files"""
  tagIds: [ID!]!

  """Whether the upload request is for general access"""
  isGeneral: Boolean!
}

"""Input for removing a tag from a file"""
input RemoveFileTagInput {
  """ID of the file being untagged"""
  _id: ID!

  """ID of the tag being removed"""
  tagId: ID!

  """Whether the upload request is for general access"""
  isGeneral: Boolean
}
